services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: portfolio_dashboard_development
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/portfolio_dashboard_development
      RAILS_ENV: development
    volumes:
      - ./backend:/rails
      - bundle_cache:/usr/local/bundle
    depends_on:
      - db
    networks:
      - app-network
    stdin_open: true
    tty: true

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:3000"
    environment:
      - NODE_ENV=development
      - NUXT_API_BASE_URL=http://backend:3000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - app-network
    stdin_open: true
    tty: true

volumes:
  postgres_data:
  bundle_cache:

networks:
  app-network:
    driver: bridge